name: Deploy Streamlit App

# Dispara el workflow al hacer push a main (ajústalo si usas otra rama)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Instala Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Instala dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt boto3 s3fs

      # 4) Ejecuta tu app / comandos, con las credenciales en env vars
      - name: Run Streamlit
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME:       ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          # Opcional: verifica conexión a S3
          # Finalmente, arranca la app
          streamlit run ui.py
